#!/bin/bash

if [ -z "$NGINX_PORT" ]; then
	export NGINX_PORT=80
fi

if [ -z "$NGINX_TLS" ]; then
	export NGINX_TLS=443
fi

if [ -z "$FASTCGI_PORT" ]; then
	export FASTCGI_PORT=9000
fi

if [ -z "$APP_ROOT" ]; then
	export APP_ROOT='/var/www'
fi

sed -i "s/<NGINX_PORT>/$NGINX_PORT/g" /etc/nginx/sites-available/default
sed -i "s/<NGINX_TLS>/$NGINX_TLS/g" /etc/nginx/sites-available/default
sed -i "s/<FASTCGI_PORT>/$FASTCGI_PORT/g" /etc/nginx/sites-available/default
sed -i "s/<APP_ROOT>/$(echo $APP_ROOT | sed -e 's/\\/\\\\/g' -e 's/\//\\\//g' -e 's/&/\\\&/g')/g" /etc/nginx/sites-available/default


echo "Running nginx on port $NGINX_PORT"
echo "Running nginx on port $NGINX_TLS"
echo "Running fastcgi-mono on port $FASTCGI_PORT"

# http://www.hnwatcher.com/r/1539872/Using-Runit-in-a-Docker-Container
export > /etc/envvars
exec /etc/runit/2
